[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [ValidateSet(
        "up",
        "down",
        "reset",
        "status",
        "logs",
        "app-build",
        "app-up",
        "app-down",
        "app-status",
        "app-logs"
    )]
    [string] $Command = "status"
)

$ErrorActionPreference = "Stop"
$podmanComposeVersion = "1.6.0"
$repositoryRoot = Split-Path -Parent $PSScriptRoot
$composeFile = Join-Path $repositoryRoot "compose.yaml"
$databaseEnvFile = Join-Path $repositoryRoot "backend\.env.podman"
$databasePort = if ($env:POSTGRES_PORT) { [int] $env:POSTGRES_PORT } else { 5432 }
$backendPort = if ($env:BACKEND_PORT) { [int] $env:BACKEND_PORT } else { 8000 }
$frontendPort = if ($env:FRONTEND_PORT) { [int] $env:FRONTEND_PORT } else { 5173 }

function Resolve-Executable {
    param(
        [Parameter(Mandatory)]
        [string] $CommandName,

        [Parameter(Mandatory)]
        [string[]] $CandidatePaths
    )

    $resolvedCommand = Get-Command $CommandName -ErrorAction SilentlyContinue
    if ($resolvedCommand) {
        return $resolvedCommand.Source
    }

    foreach ($candidatePath in $CandidatePaths) {
        if ($candidatePath -and (Test-Path -LiteralPath $candidatePath -PathType Leaf)) {
            return (Resolve-Path -LiteralPath $candidatePath).Path
        }
    }

    throw "Could not find $CommandName. Install it or add it to PATH."
}

$podmanPath = Resolve-Executable -CommandName "podman.exe" -CandidatePaths @(
    (Join-Path $env:LOCALAPPDATA "Programs\Podman\podman.exe"),
    (Join-Path $env:ProgramFiles "RedHat\Podman\podman.exe"),
    (Join-Path $env:ProgramFiles "Podman\podman.exe")
)
$uvPath = Resolve-Executable -CommandName "uv.exe" -CandidatePaths @(
    (Join-Path $env:USERPROFILE ".local\bin\uv.exe")
)

$env:PATH = "$(Split-Path -Parent $podmanPath);$env:PATH"
$composeArguments = @(
    "--from",
    "podman-compose==$podmanComposeVersion",
    "podman-compose",
    "--file",
    $composeFile,
    "--project-name",
    "elite-dev-challenge"
)

function Invoke-Compose {
    param(
        [Parameter(Mandatory)]
        [string[]] $Arguments
    )

    & $uvPath tool run @composeArguments @Arguments
    if ($LASTEXITCODE -ne 0) {
        exit $LASTEXITCODE
    }
}

function Test-TcpPort {
    param(
        [Parameter(Mandatory)]
        [string] $ComputerName,

        [Parameter(Mandatory)]
        [int] $Port
    )

    $client = [System.Net.Sockets.TcpClient]::new()
    try {
        $connection = $client.ConnectAsync($ComputerName, $Port)
        return $connection.Wait(2000) -and $client.Connected
    }
    catch {
        return $false
    }
    finally {
        $client.Dispose()
    }
}

function Resolve-PublishedPortHost {
    param(
        [Parameter(Mandatory)]
        [int] $Port
    )

    $publishedHostName = "127.0.0.1"

    if (-not (Test-TcpPort -ComputerName $publishedHostName -Port $Port)) {
        $machineAddresses = & $podmanPath machine ssh podman-machine-default `
            "ip -4 -o addr show scope global"
        $machineAddressText = $machineAddresses -join "`n"
        if ($LASTEXITCODE -ne 0 -or $machineAddressText -notmatch "eth0\s+inet\s+([0-9.]+)") {
            throw "PostgreSQL is healthy, but the Podman machine address could not be resolved."
        }

        $publishedHostName = $Matches[1]
    }

    if (-not (Test-TcpPort -ComputerName $publishedHostName -Port $Port)) {
        throw "The published container port is not reachable from Windows on $publishedHostName`:$Port."
    }

    return $publishedHostName
}

function Write-DatabaseEnvironment {
    $databaseHostName = Resolve-PublishedPortHost -Port $databasePort

    @(
        "# Generated by scripts/podman-compose.ps1. Do not commit.",
        "DATABASE_URL=postgresql+psycopg://elite:elite@$databaseHostName`:$databasePort/elite_dev"
    ) | Set-Content -LiteralPath $databaseEnvFile -Encoding utf8

    Write-Output "Backend database connection: $databaseHostName`:$databasePort"
}

function Test-PostgresIsHealthy {
    return Test-ProjectServiceIsHealthy -ServiceName "postgres"
}

function Get-ProjectServiceContainerId {
    param(
        [Parameter(Mandatory)]
        [string] $ServiceName
    )

    $containerJson = & $podmanPath ps --format json
    if ($LASTEXITCODE -ne 0) {
        return $null
    }

    $container = $containerJson |
        ConvertFrom-Json |
        Where-Object {
            $_.State -eq "running" -and
            $_.Labels.'io.podman.compose.project' -eq "elite-dev-challenge" -and
            $_.Labels.'io.podman.compose.service' -eq $ServiceName
        } |
        Select-Object -First 1

    return $container.Id
}

function Test-ProjectServiceIsHealthy {
    param(
        [Parameter(Mandatory)]
        [string] $ServiceName
    )

    $containerId = Get-ProjectServiceContainerId -ServiceName $ServiceName

    if ($LASTEXITCODE -ne 0 -or -not $containerId) {
        return $false
    }

    $healthStatus = & $podmanPath inspect --format "{{.State.Health.Status}}" $containerId
    return $LASTEXITCODE -eq 0 -and $healthStatus -eq "healthy"
}

function Wait-ProjectServicesHealthy {
    param(
        [Parameter(Mandatory)]
        [string[]] $ServiceNames,

        [Parameter(Mandatory)]
        [int] $TimeoutSeconds
    )

    $deadline = [DateTimeOffset]::UtcNow.AddSeconds($TimeoutSeconds)
    do {
        $unhealthyServices = @(
            $ServiceNames | Where-Object {
                -not (Test-ProjectServiceIsHealthy -ServiceName $_)
            }
        )

        if ($unhealthyServices.Count -eq 0) {
            Write-Output "Requested services are healthy."
            return
        }

        Start-Sleep -Seconds 2
    } while ([DateTimeOffset]::UtcNow -lt $deadline)

    throw "Timed out waiting for healthy services: $($unhealthyServices -join ', ')."
}

switch ($Command) {
    "up" {
        if (Test-PostgresIsHealthy) {
            Write-Output "PostgreSQL is already healthy; reusing the running project container."
            Write-DatabaseEnvironment
            break
        }

        Invoke-Compose -Arguments @(
            "up",
            "--detach",
            "--wait",
            "--wait-timeout",
            "60",
            "postgres"
        )
        Write-DatabaseEnvironment
    }
    "down" {
        Invoke-Compose -Arguments @("down", "--remove-orphans")
        if (Test-Path -LiteralPath $databaseEnvFile -PathType Leaf) {
            Remove-Item -LiteralPath $databaseEnvFile
        }
    }
    "reset" {
        Invoke-Compose -Arguments @("down", "--volumes", "--remove-orphans")
        Invoke-Compose -Arguments @(
            "up",
            "--detach",
            "--wait",
            "--wait-timeout",
            "60",
            "postgres"
        )
        Write-DatabaseEnvironment
    }
    "status" {
        Invoke-Compose -Arguments @("ps", "postgres")
    }
    "logs" {
        Invoke-Compose -Arguments @("logs", "--tail", "100", "postgres")
    }
    "app-build" {
        Invoke-Compose -Arguments @("build", "backend", "frontend")
    }
    "app-up" {
        Invoke-Compose -Arguments @("up", "--detach", "postgres")
        Wait-ProjectServicesHealthy -ServiceNames @("postgres") -TimeoutSeconds 60

        if (-not $env:PUBLIC_HOST) {
            $env:PUBLIC_HOST = Resolve-PublishedPortHost -Port $databasePort
        }

        Invoke-Compose -Arguments @("up", "--detach", "--build")
        Wait-ProjectServicesHealthy `
            -ServiceNames @("postgres", "backend", "frontend") `
            -TimeoutSeconds 240
        Write-DatabaseEnvironment
        Write-Output "Frontend: http://$($env:PUBLIC_HOST):$frontendPort"
        Write-Output "Backend: http://$($env:PUBLIC_HOST):$backendPort/api"
        Write-Output "Swagger: http://$($env:PUBLIC_HOST):$backendPort/docs"
    }
    "app-down" {
        Invoke-Compose -Arguments @("down", "--remove-orphans")
        if (Test-Path -LiteralPath $databaseEnvFile -PathType Leaf) {
            Remove-Item -LiteralPath $databaseEnvFile
        }
    }
    "app-status" {
        Invoke-Compose -Arguments @("ps")
    }
    "app-logs" {
        Invoke-Compose -Arguments @("logs", "--tail", "100")
    }
}
