[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [ValidateSet("up", "down", "reset", "status", "logs")]
    [string] $Command = "status"
)

$ErrorActionPreference = "Stop"
$podmanComposeVersion = "1.6.0"
$repositoryRoot = Split-Path -Parent $PSScriptRoot
$composeFile = Join-Path $repositoryRoot "compose.yaml"
$databaseEnvFile = Join-Path $repositoryRoot "backend\.env.podman"
$databasePort = if ($env:POSTGRES_PORT) { [int] $env:POSTGRES_PORT } else { 5432 }

function Resolve-Executable {
    param(
        [Parameter(Mandatory)]
        [string] $CommandName,

        [Parameter(Mandatory)]
        [string[]] $CandidatePaths
    )

    $resolvedCommand = Get-Command $CommandName -ErrorAction SilentlyContinue
    if ($resolvedCommand) {
        return $resolvedCommand.Source
    }

    foreach ($candidatePath in $CandidatePaths) {
        if ($candidatePath -and (Test-Path -LiteralPath $candidatePath -PathType Leaf)) {
            return (Resolve-Path -LiteralPath $candidatePath).Path
        }
    }

    throw "Could not find $CommandName. Install it or add it to PATH."
}

$podmanPath = Resolve-Executable -CommandName "podman.exe" -CandidatePaths @(
    (Join-Path $env:LOCALAPPDATA "Programs\Podman\podman.exe"),
    (Join-Path $env:ProgramFiles "RedHat\Podman\podman.exe"),
    (Join-Path $env:ProgramFiles "Podman\podman.exe")
)
$uvPath = Resolve-Executable -CommandName "uv.exe" -CandidatePaths @(
    (Join-Path $env:USERPROFILE ".local\bin\uv.exe")
)

$env:PATH = "$(Split-Path -Parent $podmanPath);$env:PATH"
$composeArguments = @(
    "--from",
    "podman-compose==$podmanComposeVersion",
    "podman-compose",
    "--file",
    $composeFile,
    "--project-name",
    "elite-dev-challenge"
)

function Invoke-Compose {
    param(
        [Parameter(Mandatory)]
        [string[]] $Arguments
    )

    & $uvPath tool run @composeArguments @Arguments
    if ($LASTEXITCODE -ne 0) {
        exit $LASTEXITCODE
    }
}

function Test-TcpPort {
    param(
        [Parameter(Mandatory)]
        [string] $ComputerName,

        [Parameter(Mandatory)]
        [int] $Port
    )

    $client = [System.Net.Sockets.TcpClient]::new()
    try {
        $connection = $client.ConnectAsync($ComputerName, $Port)
        return $connection.Wait(2000) -and $client.Connected
    }
    catch {
        return $false
    }
    finally {
        $client.Dispose()
    }
}

function Write-DatabaseEnvironment {
    $databaseHostName = "127.0.0.1"

    if (-not (Test-TcpPort -ComputerName $databaseHostName -Port $databasePort)) {
        $machineAddresses = & $podmanPath machine ssh podman-machine-default `
            "ip -4 -o addr show scope global"
        $machineAddressText = $machineAddresses -join "`n"
        if ($LASTEXITCODE -ne 0 -or $machineAddressText -notmatch "eth0\s+inet\s+([0-9.]+)") {
            throw "PostgreSQL is healthy, but the Podman machine address could not be resolved."
        }

        $databaseHostName = $Matches[1]
    }

    if (-not (Test-TcpPort -ComputerName $databaseHostName -Port $databasePort)) {
        throw "PostgreSQL is not reachable from Windows on $databaseHostName`:$databasePort."
    }

    @(
        "# Generated by scripts/podman-compose.ps1. Do not commit.",
        "DATABASE_URL=postgresql+psycopg://elite:elite@$databaseHostName`:$databasePort/elite_dev"
    ) | Set-Content -LiteralPath $databaseEnvFile -Encoding utf8

    Write-Output "Backend database connection: $databaseHostName`:$databasePort"
}

switch ($Command) {
    "up" {
        Invoke-Compose -Arguments @("up", "--detach", "--wait", "--wait-timeout", "60")
        Write-DatabaseEnvironment
    }
    "down" {
        Invoke-Compose -Arguments @("down", "--remove-orphans")
        if (Test-Path -LiteralPath $databaseEnvFile -PathType Leaf) {
            Remove-Item -LiteralPath $databaseEnvFile
        }
    }
    "reset" {
        Invoke-Compose -Arguments @("down", "--volumes", "--remove-orphans")
        Invoke-Compose -Arguments @("up", "--detach", "--wait", "--wait-timeout", "60")
        Write-DatabaseEnvironment
    }
    "status" {
        Invoke-Compose -Arguments @("ps")
    }
    "logs" {
        Invoke-Compose -Arguments @("logs", "--tail", "100")
    }
}
